import type { GeoObject } from "@/entities/geo-object/model/types";
import type { MapLayer } from "@/entities/map-layer/model/types";

export const MOCK_DATASETS = [
  { id: "msk", title: "Москва — все объекты" },
  { id: "spb", title: "Санкт-Петербург" },
  { id: "kzn", title: "Казань" },
] as const;

export const MOCK_LAYERS: MapLayer[] = [
  {
    id: "transport",
    title: "Транспорт",
    children: [
      { id: "stops", title: "Остановки", count: 4 },
      { id: "routes", title: "Маршруты", count: 2 },
    ],
  },
  {
    id: "infra",
    title: "Инфраструктура",
    children: [
      { id: "buildings", title: "Здания", count: 6 },
      { id: "parks", title: "Парки", count: 2 },
      { id: "water", title: "Водоёмы", count: 1 },
    ],
  },
  { id: "services", title: "Сервисы", count: 3 },
];

export const MOCK_OBJECTS: GeoObject[] = [
  {
    id: "1",
    title: "Тверская, 7",
    subtitle: "Здание · buildings",
    layerId: "buildings",
    coords: [37.606, 55.761],
    address: "ул. Тверская, 7, Москва",
    props: { Этажей: "5", Год: "1903", Тип: "Жилой дом" },
  },
  {
    id: "2",
    title: "Ост. Охотный ряд",
    subtitle: "Остановка · stops",
    layerId: "stops",
    coords: [37.617, 55.758],
    address: "Охотный ряд, Москва",
    props: { Маршруты: "м1, м2, 144", Павильон: "Да" },
  },
  {
    id: "3",
    title: "Парк Горького",
    subtitle: "Парк · parks",
    layerId: "parks",
    coords: [37.601, 55.73],
    address: "ул. Крымский Вал, 9",
    props: { Площадь: "219 га", Вход: "Свободный" },
  },
  {
    id: "4",
    title: "Москва-река",
    subtitle: "Водоём · water",
    layerId: "water",
    coords: [37.62, 55.748],
    address: "Набережная Москвы-реки",
    props: { Длина: "502 км", Судоходство: "Да" },
  },
  {
    id: "5",
    title: "БЦ Легенда",
    subtitle: "Здание · buildings",
    layerId: "buildings",
    coords: [37.64, 55.77],
    address: "ул. Лесная, 43",
    props: { Класс: "A", Этажей: "12" },
  },
  {
    id: "6",
    title: "Кофейня «Точка»",
    subtitle: "Сервис · services",
    layerId: "services",
    coords: [37.625, 55.764],
    address: "Камергерский пер., 3",
    props: { Кухня: "Кофейня", Рейтинг: "4.8" },
  },
  {
    id: "7",
    title: "Ост. Тверская",
    subtitle: "Остановка · stops",
    layerId: "stops",
    coords: [37.606, 55.765],
    address: "ул. Тверская, 15",
    props: { Маршруты: "м10, 101" },
  },
  {
    id: "8",
    title: "Маршрут м1",
    subtitle: "Маршрут · routes",
    layerId: "routes",
    coords: [37.617, 55.752],
    address: "Лубянка — Университет",
    props: { Интервал: "4 мин", Тип: "Автобус" },
  },
  {
    id: "9",
    title: "ВДНХ",
    subtitle: "Парк · parks",
    layerId: "parks",
    coords: [37.633, 55.828],
    address: "пр-т Мира, 119",
    props: { Площадь: "325 га", Год: "1939" },
  },
  {
    id: "10",
    title: "Дом на набережной",
    subtitle: "Здание · buildings",
    layerId: "buildings",
    coords: [37.609, 55.744],
    address: "ул. Серафимовича, 2",
    props: { Этажей: "12", Год: "1931" },
  },
  {
    id: "11",
    title: "Аптека 36.6",
    subtitle: "Сервис · services",
    layerId: "services",
    coords: [37.631, 55.759],
    address: "ул. Мясницкая, 24",
    props: { Круглосуточно: "Да" },
  },
  {
    id: "12",
    title: "Маршрут м2",
    subtitle: "Маршрут · routes",
    layerId: "routes",
    coords: [37.6, 55.755],
    address: "Парк Победы — Китай-город",
    props: { Интервал: "6 мин" },
  },
  {
    id: "13",
    title: "ЖК Пресня",
    subtitle: "Здание · buildings",
    layerId: "buildings",
    coords: [37.56, 55.76],
    address: "ул. Пресненский Вал, 14",
    props: { Этажей: "22" },
  },
  {
    id: "14",
    title: "Ост. Арбатская",
    subtitle: "Остановка · stops",
    layerId: "stops",
    coords: [37.6, 55.751],
    address: "ул. Арбат, 9",
    props: { Маршруты: "м2, 39" },
  },
];
